print("To multiply three numbers.")
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
num3 = int(input("Enter the third number: "))
print("The product of ", num1, ", ", num2, " and ", num3, " is ", num1*num2*num3, end=".\n", sep="")
